-- Rohablage der empfangenen ASTERIX-Datenbloecke.
-- payload enthaelt die unveraenderten Bytes, alles andere ist Herkunftsinformation.
-- Bewusst so geschrieben, dass PostgreSQL und H2 (Unit-Test) es gleichermassen verstehen.
CREATE TABLE IF NOT EXISTS asterix_raw (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    stored_at       TIMESTAMP WITH TIME ZONE NOT NULL,
    kafka_timestamp TIMESTAMP WITH TIME ZONE,
    kafka_topic     VARCHAR(255),
    kafka_partition INTEGER,
    kafka_offset    BIGINT,
    payload         BYTEA NOT NULL
);
